//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Emp_Detail> Emp_Detail { get; set; }
        public DbSet<employees1> employees1 { get; set; }
        public DbSet<tblEmployee> tblEmployees { get; set; }
        public DbSet<TestTable> TestTables { get; set; }
        public DbSet<Persons1> Persons1 { get; set; }
        public DbSet<tblEmp_Ref> tblEmp_Ref { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<employee> employees { get; set; }
    
        [EdmFunction("DBEntities", "fun1")]
        public virtual IQueryable<fun1_Result> fun1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fun1_Result>("[DBEntities].[fun1]()");
        }
    
        public virtual int sp_Persons()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Persons");
        }
    
        public virtual ObjectResult<DashBoardCounts_Result> DashBoardCounts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DashBoardCounts_Result>("DashBoardCounts");
        }
    }
}
