//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Detail
    {
        public int ID { get; set; }
        public string Emp_Details { get; set; }
        public Nullable<int> Fk_employee_id { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
