//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using WebAPI.CustomAttributes;

    public partial class employee
    {
        public employee()
        {
            this.Emp_Detail = new HashSet<Emp_Detail>();
        }
    
        public int employee_id { get; set; }
        public string last_name { get; set; }
        public string First_name { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Name { get; set; }

        [EmailValidation(ErrorMessage = "Not a Valid Email")]
        public string Email { get; set; }

        [Range(0, 100, ErrorMessage = "Age Range Must be Between 0 to 100")]
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    
        public virtual ICollection<Emp_Detail> Emp_Detail { get; set; }
    }
}
