//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmp_Ref
    {
        public int ID { get; set; }
        public int FkEmpId { get; set; }
        public string Name { get; set; }
        public int FkNewID { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
