//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public tblEmployee()
        {
            this.tblEmp_Ref = new HashSet<tblEmp_Ref>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int NewID { get; set; }
    
        public virtual ICollection<tblEmp_Ref> tblEmp_Ref { get; set; }
    }
}
